# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9de88633a88964ff6b99b7e961d91b4f36f23a7a43913f2fc7e86f1ad314425642601cde8baeec66151a9da7b70c6ba0cdb2c2c59669f70533ee95f39a762a4d

test:
  secret_key_base: 4ce4992a77805aeb2871e4c95f88a7b27a8a143e9b71aa877c1ed5ce5fea00f7a0cea9fa3e7fe59d17475b61b52878f38c53898a70ab7b7edac4cc3d768a0674

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
